### ISSUE TITLE
hal_bridge_req_t undeclared

### ISSUE THREAD

**Issue by lstrz** [pulp-platform/pulp-debug-bridge#1]
`make all` gives a bunch of `error: ‘hal_bridge_req_t’ has not been declared`. I tried browsing around the code to find where is it declared, but to no avail. What am I doing wrong?

**Comment by haugoug** [comment]
One of the submodule was too old, I've just updated it, this should fix your issue

**Comment by lstrz** [comment]
It did fix the issue!
