### ISSUE TITLE
Undefined symbols when ran

### ISSUE THREAD

**Issue by lstrz** [pulp-platform/pulp-debug-bridge#2]
After compiling (make all) and running (install/bin directory) the latest version (fresh clone), I get a stack trace:

> $ PATH=/home/lstrz/Desktop/pulp-debug-bridge/install/bin:$PATH PYTHONPATH=/home/lstrz/Desktop/pulp-debug-bridge/install/python:$PYTHONPATH LD_LIBRARY_PATH=/home/lstrz/Desktop/pulp-debug-bridge/install/lib:$LD_LIBRARY_PATH ./plpbridge --chip=pulpissimo --cable=ftdi read --addr=0x1c000000 --size=32
> Traceback (most recent call last):
>   File "./plpbridge", line 268, in <module>
>     bridge = db.get_bridge(config=config, verbose=args.verbose, binaries=args.binaries)
>   File "/home/lstrz/Desktop/pulp-debug-bridge/install/python/bridge/debug_bridge.py", line 37, in get_bridge
>     return bridge_class(config=config, binaries=binaries, verbose=verbose)
>   File "/home/lstrz/Desktop/pulp-debug-bridge/install/python/bridge/default_debug_bridge.py", line 114, in __init__
>     self.module = ctypes.CDLL(lib_path)
>   File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /home/luka/Desktop/pulp-debug-bridge/install/lib/libpulpdebugbridge.so: undefined symbol: _ZN2js25import_config_from_stringENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Am I doing something wrong?

**Comment by haugoug** [comment]
There was an issue in the build process let me know if this is now fixed

**Comment by lstrz** [comment]
Works ok now!
